### ISSUE TITLE
Compile the project against an ARM target

### ISSUE THREAD

**Issue by philss** [simd-lite/simd-json#255]
I'm trying to keep supporting ARM (32 bits) targets for our project that depends on `simd-json` and I would like to know
if it's possible to compile `simd-json` against ARM _easily_.

If it's too much work, I'm going to think in an alternative. Thanks!

PS: I'm compiling with cross and pointing to `value-trait` from main with the following:

```
$ cross build --target=arm-unknown-linux-gnueabihf --features=allow-non-simd,known-key
```

```toml
# at Cargo.toml
[patch.crates-io]
value-trait = { git = "https://github.com/simd-lite/value-trait" }
```

the output: [build-simd-json.txt](https://github.com/simd-lite/simd-json/files/9826013/build-simd-json.txt)
